### ISSUE TITLE
 Unexpected token e in JSON at position 0 at AvantationAPI.buildResponse

### ISSUE THREAD

**Issue by anbuksv** [anbuksv/avantation#3]
``` console
 Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at AvantationAPI.buildResponse (/media/storage/opensource/avantation/avantation/src/apis/avantation.ts:305:33)
    at AvantationAPI.buildEntry (/media/storage/opensource/avantation/avantation/src/apis/avantation.ts:93:43)
    at Array.forEach (<anonymous>)
    at AvantationAPI.run (/media/storage/opensource/avantation/avantation/src/apis/avantation.ts:60:30)
    at new AvantationAPI (/media/storage/opensource/avantation/avantation/src/apis/avantation.ts:54:14)
    at Avantation.run (/media/storage/opensource/avantation/avantation/src/index.ts:153:9)
    at Avantation._run (/media/storage/opensource/avantation/avantation/node_modules/@oclif/command/lib/command.js:29:31)
```

**Comment by anbuksv** [comment]
fixed from v2.0.2.
## Reason
HAR response content text is in base64 format.
